### ISSUE TITLE
Couple of problems on Twitter iOS browser(probably it is safari, safari has same problems too)

### ISSUE THREAD

**Issue by myhalici** [jdan/98.css#5] opened 2020-04-22 07:01 UTC
![38734E8A-9073-4CC1-BE59-BE7D0C862F65](https://user-images.githubusercontent.com/8976637/79950804-449c5d80-8480-11ea-92fc-087509a199ad.png)
![8F182BD9-63D2-4DFE-9644-B58AE6BC8DE7](https://user-images.githubusercontent.com/8976637/79950808-46662100-8480-11ea-9145-be9944cc08c4.png)
![3E58DB2F-1452-41F8-B84F-2453876F2142](https://user-images.githubusercontent.com/8976637/79950810-46feb780-8480-11ea-9234-593a880621db.png)

**Comment by myhalici** [comment] 2020-04-22 07:03
Dropdown has radius,
Textbox not rendered like win98,
Radio elements has strange bg when disabled and selected

**Comment by hedgehog-online** [comment] 2020-04-22 08:08
It also looks like the title bar buttons are too far away from one another in Safari: 
![image](https://user-images.githubusercontent.com/55303721/79956906-bf369e80-84bb-11ea-8d12-cf99e5090458.png)

**Comment by jdan** [comment] 2020-04-22 09:03
Thanks for the detail on this one.

**Comment by chadlavi** [comment] 2020-04-22 15:25
Reproducible in non-in-app Safari too

**Comment by loama** [comment] 2020-04-22 19:37
textbox is fixed with 
```
input[type="text"],
select,
textarea {
   -webkit-appearance: none;
   -moz-appearance: none;
   appearance: none;
   border-radius: 0;
}
```

Already sent a [PR](https://github.com/jdan/98.css/pull/31)

**Comment by jdan** [comment] 2020-04-25 16:09
Looks like these have all been addressed <3. Left one straggler in #61. Thanks all!

**Closed by jdan** 2020-04-25 16:09 UTC
