### ISSUE TITLE
98.css import wrapper component instead of applying to whole application

### ISSUE THREAD

**Issue by seanwessmith** [jdan/98.css#157] opened 2023-02-09 13:42 UTC
I would love a React Component wrapper version of this. For my personal project I just want the 98.css applied to one portion of my program. However, the current implementation applies the css broadly to every component. 

I propose something like:

```tsx
import CSS98 from '98.css';

const Main = () => {
  return (
  <CSS98>
        <div>
           <h1>demo</h1>
        </div>
  </CSS98>
  )
}
export default Main;
```

**Comment by juanigaray** [comment] 2023-03-01 14:31
This is a good idea for React projects, but it falls outside of the scope of this repo. By design, this project just outputs a CSS file with zero javascript. I'll close the issue as off-scope.

**Closed by juanigaray** 2023-03-01 14:31 UTC

**Comment by seanwessmith** [comment] 2023-03-01 14:33
Fair enough. Although I think it applies to any html project, i'm not sure of a way to use 98.css in an html/css/js without having it modify all html elements.

**Comment by juanigaray** [comment] 2023-03-01 22:31
I imagine you could use something like SCSS and paste the entire CSS (which is not that much) into the scope of a parent selector, like

```scss
.my-98css-scope {
    /* The entire 98.css CSS goes here... */
}
```

and then 

```html
<section className="not-98">This is not touched by 98css</section>
<section className="my-98css-scope">This is!</section>
```
